services:
  # PostgreSQL Database
  db:
    image: pgvector/pgvector:pg15
    container_name: django_postgres_pgvector
    environment:
      POSTGRES_DB: django_crm_db
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: django_secure_password_2024
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Your Application
  app:
    image: ${DOCKER_USERNAME}/korraai:latest
    container_name: korra-ai
    ports:
      - "7000:7000"
    environment:
      # Database connection settings
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=django_crm_db
      - DB_USER=django_user
      - DB_PASSWORD=django_secure_password_2024
      # Add other environment variables your app needs
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data: