# Generated by Django 5.2.3 on 2025-06-20 10:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('leads', '0001_initial'),
        ('platforms', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_conversation_id', models.CharField(max_length=255)),
                ('conversation_type', models.CharField(max_length=50)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('current_handler_type', models.CharField(max_length=10)),
                ('ai_enabled', models.BooleanField(default=True)),
                ('ai_paused_at', models.DateTimeField(blank=True, null=True)),
                ('ai_pause_reason', models.CharField(blank=True, max_length=255)),
                ('can_ai_resume', models.BooleanField(default=True)),
                ('handover_reason', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('priority', models.CharField(max_length=20)),
                ('sentiment_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('first_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_human_response_at', models.DateTimeField(blank=True, null=True)),
                ('last_ai_response_at', models.DateTimeField(blank=True, null=True)),
                ('response_due_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_paused_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_paused_conversations', to=settings.AUTH_USER_MODEL)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_conversations', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='customers.customer')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='leads.lead')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='platforms.socialplatform')),
                ('platform_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='platforms.tenantplatformaccount')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='tenants.tenant')),
            ],
            options={
                'db_table': 'conversations',
                'unique_together': {('tenant', 'platform', 'external_conversation_id')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_message_id', models.CharField(max_length=255)),
                ('message_type', models.CharField(max_length=50)),
                ('direction', models.CharField(max_length=20)),
                ('sender_type', models.CharField(max_length=20)),
                ('sender_id', models.UUIDField(blank=True, null=True)),
                ('sender_name', models.CharField(blank=True, max_length=255)),
                ('content_encrypted', models.TextField()),
                ('content_hash', models.CharField(max_length=64)),
                ('raw_content', models.JSONField(default=dict)),
                ('attachments', models.JSONField(default=list)),
                ('ai_processed', models.BooleanField(default=False)),
                ('ai_intent', models.CharField(blank=True, max_length=100)),
                ('ai_entities', models.JSONField(default=dict)),
                ('ai_sentiment', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ai_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('delivery_status', models.CharField(blank=True, max_length=50)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('platform_timestamp', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.conversation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tenants.tenant')),
            ],
            options={
                'db_table': 'messages',
                'unique_together': {('tenant', 'conversation', 'external_message_id')},
            },
        ),
        migrations.CreateModel(
            name='MessageReadStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('read_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to='conversations.message')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_read_statuses', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_read_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'message_read_status',
                'indexes': [models.Index(fields=['tenant', 'user', 'read_at'], name='message_rea_tenant__a8c96b_idx'), models.Index(fields=['message', 'user'], name='message_rea_message_6d3035_idx')],
                'unique_together': {('message', 'user')},
            },
        ),
    ]
