# Generated by Django 5.2.3 on 2025-06-18 19:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageReadStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('read_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to='conversations.message')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_read_statuses', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_read_statuses', to='tenants.tenantuser')),
            ],
            options={
                'db_table': 'message_read_status',
                'indexes': [models.Index(fields=['tenant', 'user', 'read_at'], name='message_rea_tenant__a8c96b_idx'), models.Index(fields=['message', 'user'], name='message_rea_message_6d3035_idx')],
                'unique_together': {('message', 'user')},
            },
        ),
    ]
