# Generated by Django 5.2.3 on 2025-06-20 10:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0001_initial'),
        ('platforms', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_response_time_seconds', models.IntegerField(blank=True, null=True)),
                ('average_response_time_seconds', models.IntegerField(blank=True, null=True)),
                ('resolution_time_seconds', models.IntegerField(blank=True, null=True)),
                ('total_messages', models.IntegerField(default=0)),
                ('customer_messages', models.IntegerField(default=0)),
                ('agent_messages', models.IntegerField(default=0)),
                ('ai_messages', models.IntegerField(default=0)),
                ('handover_count', models.IntegerField(default=0)),
                ('ai_handling_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('customer_satisfaction_score', models.IntegerField(blank=True, null=True)),
                ('resolution_status', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='conversations.conversation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_metrics', to='tenants.tenant')),
            ],
            options={
                'verbose_name_plural': 'Conversation Metrics',
                'db_table': 'conversation_metrics',
            },
        ),
        migrations.CreateModel(
            name='DailyAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('analytics_date', models.DateField()),
                ('total_conversations', models.IntegerField(default=0)),
                ('new_conversations', models.IntegerField(default=0)),
                ('resolved_conversations', models.IntegerField(default=0)),
                ('total_messages', models.IntegerField(default=0)),
                ('new_leads', models.IntegerField(default=0)),
                ('qualified_leads', models.IntegerField(default=0)),
                ('converted_leads', models.IntegerField(default=0)),
                ('ai_handled_conversations', models.IntegerField(default=0)),
                ('ai_tokens_used', models.IntegerField(default=0)),
                ('ai_accuracy_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('avg_first_response_time_seconds', models.IntegerField(blank=True, null=True)),
                ('avg_resolution_time_seconds', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_analytics', to='platforms.socialplatform')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_analytics', to='tenants.tenant')),
            ],
            options={
                'verbose_name_plural': 'Daily Analytics',
                'db_table': 'daily_analytics',
                'unique_together': {('tenant', 'platform', 'analytics_date')},
            },
        ),
    ]
