# Generated by Django 5.2.3 on 2025-06-21 05:51

from django.db import migrations
from pgvector.django import VectorField

class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0001_initial'),
    ]

    operations = [
        # This tells Django that the field is now a VectorField
        # The actual database change was already done manually
        migrations.AlterField(
            model_name='documentembedding',
            name='embedding_vector',
            field=VectorField(dimensions=1536, null=True),
            preserve_default=False,
        ),
    ]
