# Generated by Django 5.2.3 on 2025-06-19 21:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentembedding',
            name='embedding_vector',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), help_text='Vector embeddings for similarity search using pgvector', size=None),
        ),
        migrations.AlterField(
            model_name='documentembedding',
            name='similarity_threshold',
            field=models.DecimalField(decimal_places=4, default=0.75, help_text='Minimum similarity threshold for this embedding', max_digits=5),
        ),
        migrations.AlterField(
            model_name='documentembedding',
            name='vector_dimension',
            field=models.IntegerField(help_text='Number of dimensions in the embedding vector'),
        ),
        migrations.AddIndex(
            model_name='documentembedding',
            index=models.Index(fields=['tenant', 'embedding_model'], name='document_em_tenant__cbbcad_idx'),
        ),
        migrations.AddIndex(
            model_name='documentembedding',
            index=models.Index(fields=['tenant', 'document'], name='document_em_tenant__af7f5f_idx'),
        ),
        migrations.AddIndex(
            model_name='documentembedding',
            index=models.Index(fields=['embedding_model', 'vector_dimension'], name='document_em_embeddi_73d7ca_idx'),
        ),
        migrations.AddIndex(
            model_name='documentembedding',
            index=models.Index(fields=['created_at'], name='document_em_created_702258_idx'),
        ),
    ]
