# Generated by Django 5.2.3 on 2025-06-17 18:16

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platforms', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=255)),
                ('first_name_encrypted', models.TextField(blank=True)),
                ('last_name_encrypted', models.TextField(blank=True)),
                ('email_encrypted', models.TextField(blank=True)),
                ('phone_encrypted', models.TextField(blank=True)),
                ('profile_picture_url', models.URLField(blank=True)),
                ('platform_username', models.CharField(blank=True, max_length=255)),
                ('platform_display_name', models.CharField(blank=True, max_length=255)),
                ('platform_profile_data', models.JSONField(default=dict)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('custom_fields', models.JSONField(default=dict)),
                ('acquisition_source', models.CharField(blank=True, max_length=100)),
                ('customer_lifetime_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('first_contact_at', models.DateTimeField(blank=True, null=True)),
                ('last_contact_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='platforms.socialplatform')),
                ('platform_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='platforms.tenantplatformaccount')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='tenants.tenant')),
            ],
            options={
                'db_table': 'customers',
                'unique_together': {('tenant', 'platform', 'external_id')},
            },
        ),
    ]
