# Generated by Django 5.2.3 on 2025-06-18 19:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('platforms', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_messages', models.IntegerField(default=0)),
                ('messages_sent', models.IntegerField(default=0)),
                ('messages_received', models.IntegerField(default=0)),
                ('avg_response_time_seconds', models.IntegerField(blank=True, null=True)),
                ('sentiment_trend', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], default='neutral', max_length=20)),
                ('preferred_contact_hours', models.JSONField(default=list)),
                ('most_active_day', models.CharField(blank=True, choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('last_engagement_score_update', models.DateTimeField(blank=True, null=True)),
                ('insights_generated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contact_insights',
            },
        ),
        migrations.CreateModel(
            name='ContactLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('color_code', models.CharField(blank=True, max_length=7)),
                ('description', models.TextField(blank=True)),
                ('is_system_defined', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contact_labels',
            },
        ),
        migrations.CreateModel(
            name='CustomerLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'customer_labels',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='engagement_score',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_typing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='pin_order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('away', 'Away')], default='offline', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='typing_in_conversation_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['tenant', 'is_archived', 'is_pinned'], name='customers_tenant__94bd60_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['tenant', 'status'], name='customers_tenant__9b9837_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['tenant', 'engagement_score'], name='customers_tenant__cc540e_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['tenant', 'last_contact_at'], name='customers_tenant__a0d02b_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(condition=models.Q(('is_pinned', True)), fields=['pin_order'], name='customers_pinned_order_idx'),
        ),
        migrations.AddField(
            model_name='contactinsight',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='contactinsight',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_insights', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='contactlabel',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_labels', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='customerlabel',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='customerlabel',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_assignments', to='customers.contactlabel'),
        ),
        migrations.AddField(
            model_name='customerlabel',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_labels', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='contactinsight',
            index=models.Index(fields=['tenant', 'sentiment_trend'], name='contact_ins_tenant__8534d6_idx'),
        ),
        migrations.AddIndex(
            model_name='contactinsight',
            index=models.Index(fields=['tenant', 'most_active_day'], name='contact_ins_tenant__73e87d_idx'),
        ),
        migrations.AddIndex(
            model_name='contactinsight',
            index=models.Index(fields=['insights_generated_at'], name='contact_ins_insight_3fcaf1_idx'),
        ),
        migrations.AddIndex(
            model_name='contactlabel',
            index=models.Index(fields=['tenant', 'is_system_defined'], name='contact_lab_tenant__c4eb2b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contactlabel',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='customerlabel',
            index=models.Index(fields=['tenant', 'label'], name='customer_la_tenant__ff0db6_idx'),
        ),
        migrations.AddIndex(
            model_name='customerlabel',
            index=models.Index(fields=['customer'], name='customer_la_custome_ed6857_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customerlabel',
            unique_together={('customer', 'label')},
        ),
    ]
