# Generated by Django 5.2.3 on 2025-06-17 18:16

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0001_initial'),
        ('platforms', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usage_date', models.DateField()),
                ('tokens_used', models.IntegerField()),
                ('processing_time_ms', models.IntegerField()),
                ('confidence_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('knowledge_chunks_used', models.IntegerField(default=0)),
                ('handover_triggered', models.BooleanField(default=False)),
                ('handover_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_logs', to='conversations.conversation')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_logs', to='conversations.message')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_logs', to='tenants.tenant')),
            ],
            options={
                'db_table': 'ai_usage_logs',
            },
        ),
        migrations.CreateModel(
            name='AIIntentCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('intent_key', models.CharField(max_length=50)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('color_code', models.CharField(max_length=7)),
                ('priority_score', models.IntegerField(default=0)),
                ('auto_actions', models.JSONField(default=dict)),
                ('is_system_defined', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_intent_categories', to='tenants.tenant')),
            ],
            options={
                'verbose_name_plural': 'AI Intent Categories',
                'db_table': 'ai_intent_categories',
                'unique_together': {('tenant', 'intent_key')},
            },
        ),
        migrations.CreateModel(
            name='AISentimentRange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('range_key', models.CharField(max_length=50)),
                ('display_name', models.CharField(max_length=100)),
                ('min_value', models.DecimalField(decimal_places=2, max_digits=3)),
                ('max_value', models.DecimalField(decimal_places=2, max_digits=3)),
                ('color_code', models.CharField(max_length=7)),
                ('alert_threshold', models.BooleanField(default=False)),
                ('is_system_defined', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_sentiment_ranges', to='tenants.tenant')),
            ],
            options={
                'db_table': 'ai_sentiment_ranges',
                'unique_together': {('tenant', 'range_key')},
            },
        ),
        migrations.CreateModel(
            name='TenantAISetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('system_prompt', models.TextField(blank=True)),
                ('auto_response_enabled', models.BooleanField(default=True)),
                ('response_delay_seconds', models.IntegerField(default=0)),
                ('confidence_threshold', models.DecimalField(decimal_places=2, default=0.7, max_digits=5)),
                ('knowledge_base_enabled', models.BooleanField(default=True)),
                ('max_knowledge_chunks', models.IntegerField(default=5)),
                ('similarity_threshold', models.DecimalField(decimal_places=4, default=0.75, max_digits=5)),
                ('business_hours', models.JSONField(default=dict)),
                ('escalation_keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('blocked_topics', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('handover_triggers', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_settings', to='platforms.socialplatform')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_settings', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_ai_settings',
                'unique_together': {('tenant', 'platform')},
            },
        ),
    ]
