# Generated by Django 5.2.3 on 2025-06-17 18:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPlatform',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('api_version', models.CharField(max_length=20)),
                ('webhook_config', models.JSONField(default=dict)),
                ('rate_limits', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'social_platforms',
            },
        ),
        migrations.CreateModel(
            name='TenantPlatformAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_name', models.CharField(max_length=255)),
                ('platform_account_id', models.CharField(max_length=255)),
                ('access_token_encrypted', models.TextField()),
                ('refresh_token_encrypted', models.TextField(blank=True)),
                ('webhook_secret_encrypted', models.TextField(blank=True)),
                ('account_settings', models.JSONField(default=dict)),
                ('connection_status', models.CharField(max_length=20)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_accounts', to='platforms.socialplatform')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_accounts', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_platform_accounts',
                'unique_together': {('tenant', 'platform', 'platform_account_id')},
            },
        ),
    ]
